# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import gasstation_pb2 as gasstation__pb2


class GasStationServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Healthz = channel.unary_unary(
        '/gasStation.GasStationService/Healthz',
        request_serializer=gasstation__pb2.HealthzRequest.SerializeToString,
        response_deserializer=gasstation__pb2.HealthzResponse.FromString,
        )
    self.Get = channel.unary_unary(
        '/gasStation.GasStationService/Get',
        request_serializer=gasstation__pb2.GasRequest.SerializeToString,
        response_deserializer=gasstation__pb2.GasResponse.FromString,
        )


class GasStationServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Healthz(self, request, context):
    """Health is empty method for checking service started
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Get(self, request, context):
    """Get returns list of gas value
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GasStationServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Healthz': grpc.unary_unary_rpc_method_handler(
          servicer.Healthz,
          request_deserializer=gasstation__pb2.HealthzRequest.FromString,
          response_serializer=gasstation__pb2.HealthzResponse.SerializeToString,
      ),
      'Get': grpc.unary_unary_rpc_method_handler(
          servicer.Get,
          request_deserializer=gasstation__pb2.GasRequest.FromString,
          response_serializer=gasstation__pb2.GasResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'gasStation.GasStationService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
